//! The read-only world-query surface (FR-WORLD-701, contracts/world-queries.md):
//! pure functions over a [`WorldSnapshot`]. The snapshot is **structurally
//! truth-free** — it carries belief + public catalogue/site/location/Sojournal
//! data and *no* ground-truth fields — so no query here can leak truth (R4). The
//! standing audit (`tests/audit.rs`) enforces this over the whole surface.

use crate::belief::Priors;
use crate::belief::{BeliefChange, FactionId, Property, PropertyEstimate, Target};
use crate::catalogue::{BodyFilter, CatalogIndex};
use crate::locations::{Locations, Resolved};
use crate::module::WorldSlice;
use crate::observe::BeliefMap;
use crate::sites::{Placement, PpCategory, Sites};
use crate::sojournal::{Sojournal, SojournalEntry};
use serde::{Deserialize, Serialize};
use sojourn_astro::{BodyId, Catalog};
use sojourn_core::{CoreError, SimCore};

/// Public projection of a catalogue body (no truth).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct BodyView {
    /// Identity.
    pub id: BodyId,
    /// Name identifier.
    pub name_id: String,
    /// Gravitational parameter (m³/s²).
    pub mu: f64,
    /// Mean radius (m).
    pub radius: f64,
    /// Far-field gravity flag.
    pub gravitating: bool,
    /// Divert eligibility.
    pub divertible: bool,
    /// Parent body.
    pub parent: Option<BodyId>,
    /// Whether this body was generated by prospecting.
    pub generated: bool,
}

/// Public projection of a site (catalogue-level facts only; grades come via
/// `believed`).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SiteView {
    /// Data key.
    pub id: String,
    /// Anchor body.
    pub body: BodyId,
    /// Placement.
    pub placement: Placement,
    /// Planetary-protection category (cheaply knowable).
    pub pp_category: PpCategory,
    /// Resource kind id.
    pub resource: String,
    /// Surveyable properties this site exposes.
    pub properties: Vec<Property>,
}

/// A truth-free snapshot of the world for read-only queries.
pub struct WorldSnapshot {
    /// Tick the snapshot was taken at.
    pub tick: u64,
    beliefs: BeliefMap,
    change_log: Vec<BeliefChange>,
    catalog: Catalog, // base ∪ generated
    index: CatalogIndex,
    sites: Sites,
    priors: Priors,
    locations: Locations,
    sojournal: Sojournal,
    generated: std::collections::BTreeSet<BodyId>,
}

impl WorldSnapshot {
    /// Extract a snapshot from a running kernel at the current tick boundary.
    /// Projects belief + public data only — the ground-truth store is never read.
    pub fn from_core(
        core: &SimCore,
        world: &crate::module::WorldModule,
    ) -> Result<WorldSnapshot, CoreError> {
        let tick = core.status().tick;
        core.with_slice("world", |slice| {
            let s = slice
                .as_any()
                .downcast_ref::<WorldSlice>()
                .expect("world slice type");
            let generated: std::collections::BTreeSet<BodyId> =
                s.generated.keys().copied().collect();
            let catalog = world.catalog.with_generated(s.generated.values().cloned());
            let index = CatalogIndex::build(&catalog);
            WorldSnapshot {
                tick,
                beliefs: s.beliefs.clone(),
                change_log: s.change_log.clone(),
                catalog,
                index,
                sites: world.sites.clone(),
                priors: world.priors.clone(),
                locations: world.locations.clone(),
                sojournal: world.sojournal.clone(),
                generated,
            }
        })
    }

    /// The merged catalogue (base ∪ generated) — e.g. to build an `AstroSnapshot`
    /// in which a generated body is a first-class planning target (FR-WORLD-502).
    pub fn merged_catalog(&self) -> &Catalog {
        &self.catalog
    }

    // --- Catalogue queries (indexed, FR-WORLD-701) ---------------------------

    /// Bodies matching a filter (indexed; never a full scan).
    pub fn catalogue(&self, filter: &BodyFilter) -> Vec<BodyView> {
        self.index
            .query(&self.catalog, filter)
            .into_iter()
            .map(|b| self.body_view(b))
            .collect()
    }

    /// A single body view.
    pub fn body(&self, id: BodyId) -> Option<BodyView> {
        self.catalog.body(id).map(|b| self.body_view(b))
    }

    /// Total bodies (base + generated).
    pub fn body_count(&self) -> usize {
        self.index.len()
    }

    fn body_view(&self, b: &sojourn_astro::BodyDef) -> BodyView {
        BodyView {
            id: b.id,
            name_id: b.name_id.clone(),
            mu: b.mu,
            radius: b.radius,
            gravitating: b.gravitating,
            divertible: b.divertible,
            parent: b.parent,
            generated: self.generated.contains(&b.id),
        }
    }

    // --- Sites ---------------------------------------------------------------

    /// Sites anchored to a body (catalogue-level facts).
    pub fn sites_on(&self, body: BodyId) -> Vec<SiteView> {
        self.sites
            .on_body(body)
            .iter()
            .filter_map(|&sid| {
                self.sites.def(sid).map(|d| SiteView {
                    id: d.id.clone(),
                    body: d.body,
                    placement: d.placement,
                    pp_category: d.pp_category,
                    resource: d.resource.clone(),
                    properties: d.properties.iter().map(|pt| pt.property).collect(),
                })
            })
            .collect()
    }

    // --- Belief (never truth) ------------------------------------------------

    /// What faction `f` believes about `target`'s `property` (the honest default
    /// prior if it has never observed it). **Never** returns ground truth.
    pub fn believed(
        &self,
        f: FactionId,
        target: Target,
        property: Property,
    ) -> Option<PropertyEstimate> {
        self.priors.model(property)?; // unknown property ⇒ None
        let est = self
            .beliefs
            .get(&(f, target, property))
            .copied()
            .unwrap_or_else(|| self.priors.prior_for(property));
        Some(self.priors.decode(property, est))
    }

    /// Resolve a site data key to a belief `Target` (callers reference sites by
    /// key, not the internal `SiteId`).
    pub fn site_target(&self, key: &str) -> Option<Target> {
        self.sites.resolve(key).map(Target::Site)
    }

    /// What faction `f` believes about a site's property (by site key).
    pub fn believed_site(
        &self,
        f: FactionId,
        site_key: &str,
        property: Property,
    ) -> Option<PropertyEstimate> {
        let t = self.site_target(site_key)?;
        self.believed(f, t, property)
    }

    /// How certain faction `f` is about a site's property (by site key).
    pub fn certainty_site(&self, f: FactionId, site_key: &str, property: Property) -> Option<f64> {
        let t = self.site_target(site_key)?;
        self.certainty(f, t, property)
    }

    /// How certain faction `f` is about `target`'s `property`, in `[0, 1]`
    /// (0 = prior, →1 as belief tightens to the floor).
    pub fn certainty(&self, f: FactionId, target: Target, property: Property) -> Option<f64> {
        let m = self.priors.model(property)?;
        let est = self
            .beliefs
            .get(&(f, target, property))
            .copied()
            .unwrap_or_else(|| self.priors.prior_for(property));
        Some((1.0 - est.var / m.prior_var).clamp(0.0, 1.0))
    }

    /// Belief changes for faction `f` strictly after `since_tick` (for UI refresh).
    pub fn belief_delta_since(&self, f: FactionId, since_tick: u64) -> Vec<BeliefChange> {
        self.change_log
            .iter()
            .filter(|c| c.faction == f && c.tick > since_tick)
            .copied()
            .collect()
    }

    // --- Locations -----------------------------------------------------------

    /// All location ids.
    pub fn locations(&self) -> Vec<String> {
        self.locations.ids().map(str::to_string).collect()
    }

    /// Resolve a location at a time (defaults to the snapshot tick).
    pub fn resolve_location(&self, id: &str, t_ns: Option<i64>) -> Option<Resolved> {
        let t = t_ns.unwrap_or(self.tick as i64 * 1_000_000_000);
        self.locations
            .resolve(id, &self.catalog, &std::collections::BTreeMap::new(), t)
    }

    // --- Sojournal -----------------------------------------------------------

    /// A Sojournal entry by id.
    pub fn sojournal(&self, id: &str) -> Option<&SojournalEntry> {
        self.sojournal.entry(id)
    }
}
